-- ==========================================
-- SCRIPT DE CONFIGURATION BASE DE DONNEES
-- ==========================================
-- Copiez tout ce contenu et collez-le dans l'éditeur SQL de votre projet Supabase.

-- 1. Table des Clients (Achats)
create table if not exists customers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  stripe_customer_id text,
  access_level text, -- 'SOLO', 'PRO', 'VIP' || 'pack' in old mental model
  amount_paid numeric,
  expires_at timestamptz,
  created_at timestamptz default now(),
  reminder_sent boolean default false,
  discord_id text,
  wallet_address text,
  claimed boolean default false,
  claimed_at timestamptz,
  claim_tx_hash text
);

-- 2. Table des Rendez-vous (Calendly)
create table if not exists appointments (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  event_uri text,
  invitee_uri text unique,
  status text,
  start_time timestamptz,
  end_time timestamptz,
  created_at timestamptz default now(),
  calendly_event_type text
);

-- 3. Sécurité (Row Level Security)
alter table customers enable row level security;
alter table appointments enable row level security;

-- Optionnel: Index pour accélérer les recherches par email
create index if not exists customers_email_idx on customers (email);
create index if not exists appointments_email_idx on appointments (email);

-- ==========================================
-- FIN DU SCRIPT
-- ==========================================
