-- Execute this in your Supabase SQL Editor

create table if not exists appointments (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  event_uri text,
  invitee_uri text unique,
  status text,
  start_time timestamptz,
  end_time timestamptz,
  created_at timestamptz default now(),
  calendly_event_type text
);

-- Enable RLS (Optional but recommended if exposed, though this is backend-only access usually)
alter table appointments enable row level security;

-- Policy: Only service role (backend) can insert/select by default if no policies added.
-- Since we use supabase-js service role key in our API, this is fine.
